### ISSUE TITLE
Part 3 - Question 2 - a,b,c is wrong

### ISSUE THREAD

**Issue by MohamedWSalah** [kandluis/cs155-projects#1]
the answers u got for part 3 question 2 - a b c is wrong , u made the attacker an IP that has port 80 , while the attacker suppose to be this one 171.64.1.234, since he is the one who send requests to 10.30.22.101 ( Victim ) but everytime on a different port which means he is "PortScanning" this target.

**Comment by kandluis** [comment]
Thanks for the feedback! I think you're right about identifying the port-scanner rather.
